### ISSUE TITLE
Add page to List folder

### ISSUE THREAD

**Issue by SClarkTwinSoft** [Aymkdn/OrgChart-JS-Sharepoint#3]
"You can create a new .aspx or .html file in the same folder than your list (e.g.  http://your.sharepoint.com/root/directory/Lists/Org Chart/Show.aspx )"

How do you add a page to the same folder as a list?
Is this a requirement? 
Most pages get added to a document library, like Site Pages or Site Assets, please advise.

**Comment by Aymkdn** [comment]
No, this is not a requirement. You can create your page wherever you want.
