### ISSUE TITLE
Show.aspx?

### ISSUE THREAD

**Issue by SClarkTwinSoft** [Aymkdn/OrgChart-JS-Sharepoint#4]
" http://your.sharepoint.com/root/directory/Lists/Org Chart/Show.aspx?tier=1&root=john_doe "
Why is Show.aspx called here?  What should be in this file?

There is an OrgChart.html, when and how does it get called?

**Comment by Aymkdn** [comment]
This is a very old project, but it looks like you don't need the OrgChart.html at all.

**Comment by SClarkTwinSoft** [comment]
You really need to update your instructions. They're not helpful.
