### ISSUE TITLE
FitText reference

### ISSUE THREAD

**Issue by SClarkTwinSoft** [Aymkdn/OrgChart-JS-Sharepoint#5]
There's no reference to FitText, so does this need to be added to the .html page, like the other references to .js scripts?

**Comment by Aymkdn** [comment]
I'm on vacation, far away from home. I'll look at your issues on my return, next week.

**Comment by Aymkdn** [comment]
FitText is already into [orgchart.js](https://github.com/Aymkdn/OrgChart-JS-Sharepoint/blob/master/orgchart.js#L24)

**Comment by SClarkTwinSoft** [comment]
"FitText is already into orgchart.js"

Does this mean that the code that is in FitText.js is already in OrgChart.js?  I'm in an environment that doesn't freely access the internet, so, I assume that I have to put FitText.js within my environment, then make reference to that file in my code.  So, in your section "Create your HTML Page", you refer to the other .js files, do I need to do the same with FitText, or else how should I make this reference?

**Comment by Aymkdn** [comment]
It means you don't need to take care of FitText at all. Just ignore it. The code is already included into the orgchart.js file... see: https://github.com/Aymkdn/OrgChart-JS-Sharepoint/blob/master/orgchart.js#L24
